import { FightStatus } from '../../domain/value-objects/fight-status.enum';

export type FightListItemView = {
  id?: number;
  competitionId: number;
  categoryId: number | null;
  categoryName: string | null;
  keyGroupId: number | null;
  keyGroupName: string | null;
  areaId: number | null;
  areaName: string | null;
  status: FightStatus;
  round: number;
  order: number;
  athleteAId: number | null;
  athleteAName: string | null;
  academyAName: string | null;
  athleteBId: number | null;
  athleteBName: string | null;
  academyBName: string | null;
  winnerId: number | null;
  winnerName: string | null;
  loserId: number | null;
  nextFightId: number | null;
  nextFightSlot: 'A' | 'B' | null;
  createdManually: boolean;
  isWo: boolean;
  winType: string | null;
  startedAt: Date | null;
  finishedAt: Date | null;
  orderIndex: number;
};
